### ISSUE TITLE
0x7A7A6572恩师大人敬启者

### ISSUE THREAD

**Issue by shediaonaren** [0x7A7A6572/self-rule#4]
0x7A7A6572恩师大人敬启者，小弟摩罗星。今年27，一事无成，幸好心术还算良正。乞求师父收我为徒，让我有一技在
身，他日行走江湖，锄强扶弱，为社会服务，为国家捐躯，为自由，爱自由，自由万岁！我的wx是dmcanglong

**Comment by 0x7A7A6572** [comment]
> 0x7A7A6572恩师大人敬启者，小弟摩罗星。今年27，一事无成，幸好心术还算良正。乞求师父收我为徒，让我有一技在 身，他日行走江湖，锄强扶弱，为社会服务，为国家捐躯，为自由，爱自由，自由万岁！我的wx是dmcanglong

可以一起交流学习😂
